### ISSUE TITLE
`data_pull()` return a list of project resources instead of a vector of strings

### ISSUE THREAD

**Issue by hafen** [ki-tools/kitools-py#24]
To be consistent with `data_add()`, `data_pull()` should probably return a list of project resources instead of a vector of strings. I think I originally asked for strings, but that was before I knew about the project resource return type.

**Comment by pcstout** [comment]
@hafen Only `data_add()` returns the resource object. `data_pull/push` return the absolute path(s). Should I make this change so all 3 methods return the resource object?

**Comment by hafen** [comment]
Yes I think it's good to be consistent. Unless you have any reservations about it.

**Comment by pcstout** [comment]
https://github.com/ki-tools/kitools-py/pull/28

**Comment by pcstout** [comment]
https://github.com/ki-tools/kitools-py/pull/31
