### ISSUE TITLE
Update location of resources based on type

### ISSUE THREAD

**Issue by hafen** [ki-tools/kitools-py#27]
1. Core data goes in same location as always, `/data/core`
2. Discovered data is now auxiliary data and instead of `/data/discovered`, it goes in `/data/auxiliary`
3. Artifacts is now expanded to mean data, figures, tables, etc. created during an analysis, and instead of `/data/artifacts`, this goes in `/results`

**Comment by pcstout** [comment]
https://github.com/ki-tools/kitools-py/pull/30
